### PR TITLE
pkg/dashboard: setup basePath as a path prefix in routing

### PR DESCRIPTION
**Pull request by adamdecaf**
Awesome project! It works for me with a `port-forward`, but not with `-dashboard-path-prefix`. After this change I can load the dashboard with a base path (`/polaris/` in my case), but I haven't tested building a Docker image for my cluster yet. 

~~Btw, I was unable to sign the CLA at https://cla-assistant.io/fairwinds/polaris (404)~~ With `?pullRequest=201` I could sign the CLA.

### CODE REVIEW

**Comment by rbren** [comment]
Thanks for the details Adam! Sorry for the delay in response.

I think to support your use case in a backward-compatible way, we'd have to create a new flag, maybe `dashboard-mount-path`, which would get passed in alongside `basePath`. If you want to modify your PR to do that we can merge it in, or we can take a look at adding support for this in our next release.

**Comment by adamdecaf** [comment]
What about `-dashboard-web-path[-prefix]`?

**Comment by rbren** [comment]
Sounds good, I like `-dashboard-web-path-prefix`

**Comment by adamdecaf** [comment]
Reading this again it seems this PR fixes the problem ran into at https://github.com/FairwindsOps/polaris/issues/132, so I'm not sure why we need a new flag. `--dashboard-path-prefix` is already passed to `dashboard.GetRouter` so we want to merge two "path prefix" flags together?

**Comment by rbren** [comment]
🤔 you may be right. I never saw the follow-up message from troian there.

My main concern was breaking his use-case if we merged this. Seeing as it was never fixed, I'm less concerned. Will give him a day or so to respond, otherwise I'll assume this is good to go.

**Comment by adamdecaf** [comment]
cc @troian thoughts?

**Comment by troian** [comment]
Just in case I miss conversation point. Just check with version `0.4.0`. Config is still the same as in #132

**Comment by adamdecaf** [comment]
With 0.4.0 and your config from #132 the static assets are still not rendered properly? I was able to specify `--dashboard-path-prefix` and load under a `/polaris/` path locally.

**Comment by troian** [comment]
Yes. I checked 0.5.0-beta2 and that gave me same result.
Sounds like something wrong then on our side

**Comment by rbren** [comment]
@troian can you try using `0.5.0-beta3`? That incorporates this change. I think you'll also need to remove the rewrite rule in your ingress.

**Comment by adamdecaf** [comment]
I adjusted the patch a bit and it works better locally for me now. The only annoying thing is `/health` doesn't respond with a path. Instead you'd need `/polaris/health`.

**Comment by rbren** [comment]
Great! I don't think there's a good way around needing to adjust the health check, mounting `/health` on the base path and everything else on `/polaris` doesn't seem quite right. We'll adjust the liveness/readiness checks in the helm chart accordingly.

Thanks for making this change Adam, will merge now

**Pull request merged**
