### PR TITLE
Update goreleaser

### PR DESCRIPTION
**Pull request by gabegorelick**
This is needed to fix homebrew deprecation warnings, which are fixed in v0.183.0.

See https://github.com/FairwindsOps/homebrew-tap/issues/6

### CODE REVIEW

**Comment by lucasreed** [comment]
Hi @gabegorelick thanks for the contribution! Could you please sign the CLA and I think there shouldn't be an issue getting this merged.

**Comment by gabegorelick** [comment]
> Could you please sign the CLA

Sorry, I can't right now. If that's an issue, then feel free to close this.

**Comment by lucasreed** [comment]
> > Could you please sign the CLA
> 
> Sorry, I can't right now. If that's an issue, then feel free to close this.

Fair enough, we will close this and implement it in a separate PR.

**Comment by kcirrr** [comment]
Also, Goreleaser version 1.0.0 has been released already. I could create a PR for it.

**Comment by kcirrr** [comment]
I created a new PR to update the version to 1.0.0 here FairwindsOps/polaris#677

**Pull request closed without merging**
