### PR TITLE
Add Swaroop as Codeowner

### PR DESCRIPTION
**Pull request by rbren**

### CODE REVIEW

**Review by jordandoig — APPROVED** [review]
👍🏻 Ship it!

**Review by makoscafee — APPROVED** [review]

**Review by baderbuddy — APPROVED** [review]
Everyone else was approving so I wanted to join the crowd

**Comment by jordandoig** [comment]
@shaswa Want to get in on this?

**Review by shaswa — APPROVED** [review]
Thanks!

**Comment by shaswa** [comment]
> @shaswa Want to get in on this?

image

**Comment by shaswa** [comment]
Should we disable `Merge pull request` and allow only `Squash and Merge` on this repo? I just realized I didn't squash my commits from my PR 😞

**Comment by rbren** [comment]
Good call!

**Comment by rbren** [comment]
I can't figure out how to disable the other merge strategies...

**Comment by shaswa** [comment]
> I can't figure out how to disable the other merge strategies...

@rbren It should be under settings but I think only repo admin/owners can access the settings
Screen Shot 2021-01-19 at 2 03 20 PM

**Pull request merged**
