### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by rbren**

### CODE REVIEW

**Comment by mambax** [comment]
Stupid question from my side. With 1.0 the CLI 'commander' is changed to cobra we have seen (and with that how you hand in arguments afaict). Did that find a place in the new docs? Not for me I've seen it now, but we firstly struggled what changed and then finding the commit hiding it :)

**Comment by rbren** [comment]
Good question! Yes everything is documented in [usage](/docs/usage.md), but I also added a note to the CHANGELOG. Thanks for pointing that out!

**Comment by rbren** [comment]
FYI - we're just waiting on the [Quay outage](https://status.quay.io/)

**Comment by mambax** [comment]
nervous:tenor

**Pull request merged**
